[package]
name = "rust-test-suites"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["prod"]
unit = []
it = []
prod = []

[dependencies]
